[package]
name = "struct-patch-derive"
authors.workspace = true
version.workspace = true
edition.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
description.workspace = true
license.workspace = true
readme.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version =  "3", features = ["parsing"] }
syn-serde = { package = "syn-serde3", version = "0.0.1", features = ["json"], optional = true }
cargo_metadata = { version = "0.18", optional = true }

[features]
status = []
op = []
merge = []
nesting = []
substrate = [ "syn-serde", "syn/full" ]
catalyst = [ "substrate", "dep:cargo_metadata" ]
unsafe = []
box = []

[dev-dependencies]
pretty_assertions_sorted = "1.2.3"
