[package]
name = "struct-patch"
authors.workspace = true
version.workspace = true
edition.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
description.workspace = true
license.workspace = true
readme.workspace = true
rust-version.workspace = true

[dependencies]
struct-patch-derive = { version = "=0.14.1", path = "../derive" }

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"

[features]
default = ["status", "op"]
status = [
    "struct-patch-derive/status"
]
op = [
    "struct-patch-derive/op"
]
merge = [
    "struct-patch-derive/merge"
]

alloc = []
std = ["box", "option"]
box = ["alloc", "struct-patch-derive/box"]
option = []
nesting = [
    "struct-patch-derive/nesting"
]
none_as_default = ["option"]
keep_none = ["option"]
substrate = [
    "struct-patch-derive/substrate"
]
catalyst = [
    "struct-patch-derive/catalyst",
    "struct-patch-derive/substrate"
]
unsafe = [
    "struct-patch-derive/unsafe"
]

