[package]
name = "no-std-examples"
authors = ["Antonio Yang <yanganto@gmail.com>"]
version = "0.14.4"
edition = "2021"
license = "MIT"

[dependencies]
struct-patch = { path = "../../lib", default-features = false }
linked_list_allocator = "0.10"
cortex-m-rt = "0.7"
cortex-m-semihosting = "0.5"
panic-semihosting = "0.7"

[features]
default = []
box = ["struct-patch/box"]
option = ["struct-patch/option"]
nesting = ["struct-patch/nesting", "struct-patch/log"]
pure-nesting = ["struct-patch/nesting"]
simple-nesting = ["struct-patch/simple-nesting", "struct-patch/log"]

[[bin]]
name = "no-std-box"
path = "src/box.rs"

[[bin]]
name = "no-std-option"
path = "src/option.rs"

[[bin]]
name = "no-std-nesting"
path = "src/nesting.rs"
