name: Test

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build devshells
        run: |
          nix develop .#ci -c echo Build ci devshell
          nix develop .#no-std -c echo Build no-std devshell

      - name: Test lib
        run: |
          nix develop .#ci -c test no-default
          nix develop .#ci -c test std
          nix develop .#ci -c test merge
          nix develop .#ci -c test default

      - name: Test patch examples
        run: |
          nix develop .#ci -c check-patch no-default
          nix develop .#ci -c check-patch std
          nix develop .#ci -c check-patch merge
          nix develop .#ci -c check-patch option
          nix develop .#ci -c check-patch default

      - name: Test filler examples
        run: |
          nix develop .#ci -c check-filler no-default
          nix develop .#ci -c check-filler default

      - name: Test in no std
        run: nix develop .#no-std -c check-no-std

      - name: Test complex examples
        run: nix develop .#ci -c check-complex
