name: Test

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test no default features
        run: |
          nix develop .#ci -c cargo run --quiet --no-default-features --example instance
          nix develop .#ci -c cargo run --quiet --no-default-features --example filler
          nix develop .#ci -c cargo run --quiet --no-default-features --example diff
          nix develop .#ci -c cargo run --quiet --no-default-features --example json
          nix develop .#ci -c cargo run --quiet --no-default-features --example rename-patch-struct
          nix develop .#ci -c cargo run --quiet --no-default-features --example patch-attr
          nix develop .#ci -c cargo run --quiet --no-default-features --example time
          nix develop .#ci -c cargo run --quiet --no-default-features --example clap
          nix develop .#ci -c cargo run --quiet --no-default-features --features=nesting --example nesting
          nix develop .#ci -c cargo run --quiet --no-default-features --features=option --example option
          nix develop .#ci -c cargo run --quiet --no-default-features --example=log
          nix develop .#ci -c cargo run --quiet --no-default-features --example apply-by
          nix develop .#ci -c cargo run --quiet --no-default-features --features=box --example box
          nix develop .#ci -c cargo test --quiet --no-default-features

      - name: Test with std features
        run: |
          nix develop .#ci -c cargo run --quiet --features=std --example instance
          nix develop .#ci -c cargo run --quiet --features=std --example filler
          nix develop .#ci -c cargo run --quiet --features=std --example filler-op
          nix develop .#ci -c cargo run --quiet --features=std --example diff
          nix develop .#ci -c cargo run --quiet --features=std --example json
          nix develop .#ci -c cargo run --quiet --features=std --example rename-patch-struct
          nix develop .#ci -c cargo run --quiet --features=std --example patch-attr
          nix develop .#ci -c cargo run --quiet --features=std --example option
          nix develop .#ci -c cargo run --quiet --features=std --example box
          nix develop .#ci -c cargo run --quiet --features=std,nesting --example nesting
          nix develop .#ci -c cargo test --quiet --features=std

      - name: Test with merge features
        run: |
          nix develop .#ci -c cargo run --quiet --features=option,merge --example option
          nix develop .#ci -c cargo run --quiet --features=merge --example op
          nix develop .#ci -c cargo run --quiet --features=merge,nesting --example nesting
          nix develop .#ci -c cargo test --quiet --features=merge --no-default-features
          nix develop .#ci -c cargo test --quiet --features=merge

      - name: Test with option features
        run: |
          nix develop .#ci -c cargo run --quiet --features=none_as_default --example option
          nix develop .#ci -c cargo run --quiet --features=none_as_default,nesting --example nesting
          nix develop .#ci -c cargo run --quiet --features=keep_none --example option
          nix develop .#ci -c cargo run --quiet --features=keep_none,nesting --example nesting

      - name: Test with default features
        run: |
          nix develop .#ci -c cargo run --quiet --example status
          nix develop .#ci -c cargo run --quiet --example op
          nix develop .#ci -c cargo run --quiet --example clap
          nix develop .#ci -c cargo run --quiet --features=nesting --example nesting
          nix develop .#ci -c cargo run --quiet --features=nesting --example clap
          nix develop .#ci -c cargo run --quiet --example=log
          nix develop .#ci -c cargo run --quiet --example apply-by
          nix develop .#ci -c cargo run --quiet --features=box --example box
          nix develop .#ci -c cargo test --quiet

      - name: Test in no std
        run: |
          cd examples/no-std-examples
          nix develop .#no-std -c cargo run --quiet --features=box --bin no-std-box
          nix develop .#no-std -c cargo run --quiet --features=option --bin no-std-option

      - name: Test complex examples
        run: nix develop .#ci -c check-complex
